//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPoints
    {
        public int CheckPointId { get; set; }
        public Nullable<bool> Drinks { get; set; }
        public Nullable<bool> EnergyBars { get; set; }
        public Nullable<bool> Toilets { get; set; }
        public Nullable<bool> Information { get; set; }
        public Nullable<bool> Medicial { get; set; }
    }
}
