//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speed
    {
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public string Top_Speed { get; set; }
    }
}
